apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crud-app-ingress
  labels:
    app.kubernetes.io/name: crud-app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: crud-app.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: crud-app-service
            port: 
              number: 5000
